spring.application.name=users
server.port=3001

# Substitua pelo endereço do seu Keycloak e o nome do seu Realm
# URL de validação e emissão de tokens
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/facoffee

# O nome do seu realm para ser injetado na UserService
realm=facoffee

# Configurações de Conexão com o PostgreSQL do Docker
# Aponta para a nova porta livre que mapeamos no Windows
spring.datasource.url=jdbc:postgresql://localhost:5433/facoffee_users_db
spring.datasource.username=facoffee_admin
spring.datasource.password=ufms_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA

#indica que o banco usado será o postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' cria ou atualiza as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
# Exibe no console da IDE as queries SQL que o Spring executar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG